// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250822002955_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "went hiking with Guru",
                            CreatedAt = new DateTime(2025, 8, 22, 2, 29, 53, 193, DateTimeKind.Local).AddTicks(2854),
                            Title = "Went hiking"
                        },
                        new
                        {
                            Id = 2,
                            Content = "went cluping with Guru",
                            CreatedAt = new DateTime(2025, 8, 22, 2, 29, 53, 193, DateTimeKind.Local).AddTicks(2865),
                            Title = "Went Clubing"
                        },
                        new
                        {
                            Id = 3,
                            Content = "went shopping with Guru",
                            CreatedAt = new DateTime(2025, 8, 22, 2, 29, 53, 193, DateTimeKind.Local).AddTicks(2874),
                            Title = "Went Shopping"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
